### PR TITLE
Rework badges in readmes [ECR-593]

### PR DESCRIPTION
**Pull request by vitvakatu**
What do you think?

[Main readme](https://github.com/vitvakatu/exonum/tree/ecr_593/README.md)

### CODE REVIEW

**Comment by ozkriff** [comment]
What about adding explicit group names, something like
image
?

**Comment by DarkEld3r** [comment]
I like the idea of the group names. As for me, it is quite the opposite of noise: it helps to navigate through badges.

**Comment by vitvakatu** [comment]
Another question, do we need crates versions in readmes?

**Comment by ozkriff** [comment]
docs.rs badge should already show the latest version:
https://docs.rs/exonum/badge.svg

**Pull request merged**
