### PR TITLE
Reorder imports (treat all 'extern create' as thirdparty)

### PR DESCRIPTION
**Pull request by DarkEld3r**
Motivation: we had a (not described formally) convention to separate usings into three groups: first thirdparty, then `std` and finally the internal ones. I propose to treat all `external crate` usings as thirdparty just because it is a formal criteria.

The order is discussable too.

### CODE REVIEW

**Comment by alekseysidorov** [comment]
What do you think about order such this?
```rust
use std;
use foreign_crates;
use exonum_crates;
use current_crate;
```

**Comment by aleksuss** [comment]
Let's be closer to community convention ?
```rust
use third_party_crates;

use std;

use current_crate;

pub use current_crate;
```
P.S. third_party_crates include exonum's crates as external dependencies

**Comment by DarkEld3r** [comment]
I like this idea, especially because it seems that `rust-fmt` [probably](https://github.com/rust-lang-nursery/fmt-rfcs/issues/24) will probably enforce a similar order.

**Comment by DarkEld3r** [comment]
Discussed, the following order should be used:
```rust
use std;
...

use extern_crate;
...

use inner;
...

pub use something;
```

Motivation: it is a popular ordering in other crates and in the [rust-fmt RFC](https://github.com/rust-lang-nursery/fmt-rfcs/issues/24).
It can be convenient to separate our (exonum) extern crates from third-party crates, but such rule cannot be (easily) automated.

**Comment by aleksuss** [comment]
It'd be grate if you save this somewhere in a public place

**Comment by DarkEld3r** [comment]
@aleksuss We have an issue (https://github.com/exonum/exonum/issues/109 and in JIRA too) for `CONTRIBUTING.md`/`developer-notes.md`. :trollface:

**Pull request merged**
