### PR TITLE
Removed HashMap wrapper in MemoryDB

### PR DESCRIPTION
**Pull request by aleksuss**
### Description
Improve MemoryDB functionality 

Removed `HashMap` wrapper

### What kind of change does this PR introduce?

- [x] Bug fix (non-breaking change which fixes an issue)

- [ ] New feature (non-breaking change which adds functionality)

- [ ] Breaking change (fix or feature that would cause existing functionality to change)

- [ ] Other (CI-improvements, docs fixes, version bumps, clippy, rustfmt)

### Checklist:
- [x] All commits are named based on our guideline (read CONTRIBUTING.md)

- [x] Tests for the changes have been added

- [ ] Docs have been added / updated

- [ ] CHANGELOG.md have been updated

### How can we test these changes?
Unit-tests

### CODE REVIEW

**Comment by ozkriff** [comment]
> - [ ] CHANGELOG.md have been updated

Shouldn't this change be mentioned in the changelog?

**Comment by aleksuss** [comment]
Actually I don't know. There're unimportant changes.

**Comment by DarkEld3r** [comment]
We need to develop a convention for such things. On the one hand, it is an implementation detail. On the other hand, it (probably) improves performance.

**Comment by slowli** [comment]
> Improve MemoryDB functionality

Do you mean performance? (As far as I see, the functionality of `MemoryDB` isn't changed by the PR.) If so, could you please write a benchmark to compare?

Also, I may be missing something, but I'm having trouble understanding why your implementation works correctly. Wouldn't it be the case that if one name (say, `foo`) is a prefix of another name (say, `foobar`) and we call `db.iter("foo", &[])`, it would incorrectly include `foobar`'s entries into the iterator? Could you please write the corresponding test?

**Comment by aleksuss** [comment]
@slowli Yes. You're right about collision with nearest prefixes. I've missed this case. We should write more unit tests 😄

**Pull request closed without merging**
