### PR TITLE
Update CHANGELOG.md

### PR DESCRIPTION
**Pull request by dmitry-timofeev**
## Overview

---

See: https://jira.bf.local/browse/ECR-XYZW

### Definition of Done

- [ ] There are no TODOs left in the merged code
- [ ] Change is covered by automated tests
- [ ] Benchmark results are attached (if applicable)
- [ ] The [coding guidelines] are followed
- [ ] Public API has proper documentation
- [ ] Changelog is updated if needed (in case of notable or breaking changes)
- [ ] The continuous integration build passes

[coding guidelines]: https://github.com/exonum/exonum/blob/master/CONTRIBUTING.md#conventions

### CODE REVIEW

**Comment by aleksuss** [comment]
Actually, we don't add outputs in `json` format in the `CHANGELOG`. The documentation on the site is good place for it, isn't it ?

**Comment by dmitry-timofeev** [comment]
Well, it's under a spoiler. Is there a documentation reference providing complete information on the format with which it can be replaced?

**Comment by vitvakatu** [comment]
@popzxc good catch. Btw, I think that flat proofs in `dynamic_services` is a mistake, it brings problems with migration to DS.

**Comment by aleksuss** [comment]
@popzxc @vitvakatu It's not about proofs, as I can see.

**Comment by vitvakatu** [comment]
Ah, sorry, I would read PRs before writing comments :D

**Comment by popzxc** [comment]
Ah. I got triggered by the word "flat". I need to sleep more ^^"

**Pull request merged**
