### PR TITLE
Use 'ServiceFactory' as trait object

### PR DESCRIPTION
**Pull request by DarkEld3r**

### CODE REVIEW

**Comment by defuz** [comment]
@DenisKolodin Motivation?

**Comment by DarkEld3r** [comment]
@defuz It was my idea. :smile: I think that approach has two advantages:
1. It works better if we want the framework to provide some `start`/`main` function that takes additional service factories. Currently it cannot be done by function, only by macro because service factory is used as type, not as object.
2. I suppose it is better if we want to change interface into that crates service with given version.

**Comment by defuz** [comment]
@DarkEld3r, BTW is it breaking change? Do we need to update CHANGELOG?

**Comment by vldm** [comment]
Please update changelog before merge.

**Comment by alekseysidorov** [comment]
Can you also update services code?

**Pull request merged**
