### PR TITLE
Add supervisor mode in README

### PR DESCRIPTION
**Pull request by aleksuss**
## Overview

---

See: https://jira.bf.local/browse/ECR-XYZW

### Definition of Done

- [ ] There are no TODOs left in the merged code
- [ ] Change is covered by automated tests
- [ ] Benchmark results are attached (if applicable)
- [ ] The [coding guidelines] are followed
- [ ] Public API has proper documentation
- [ ] Changelog is updated if needed (in case of notable or breaking changes)
- [ ] The continuous integration build passes

[coding guidelines]: https://github.com/exonum/exonum/blob/master/CONTRIBUTING.md#conventions

### CODE REVIEW

**Comment by aleksuss** [comment]
Sadly, it is not. By the way, I though the simple mode is default as well.

**Comment by popzxc** [comment]
@aleksuss maybe then make this behaviour the default in `cli`? :)

**Comment by aleksuss** [comment]
I don't know if it really makes sense. It adds some ambiguity, doesn't it ? @slowli @alekseysidorov  what do you think ?

**Comment by slowli** [comment]
@aleksuss I think adding a default value makes sense: the default value is prominently displayed in the command help, so there shouldn't be significant ambiguity. At the same time, it would make CLI commands less verbose.

**Comment by aleksuss** [comment]
@slowli deal.

**Pull request closed without merging**
