### PR TITLE
Update logger version

### PR DESCRIPTION
**Pull request by alekseysidorov**
Just update logger version.

- Not a breaking change
- No need in updating docs
- No need in testing

### CODE REVIEW

**Comment by alekseysidorov** [comment]
There are two question:

- Lets format time in the ISO standard format.
- Maybe the `<unknown file>` and `<unknown module> are more human readable.

**Comment by DarkEld3r** [comment]
> Let's format time in the ISO standard format.

I think this is a nice idea for a separate pull request. :smile:

**Comment by matklad** [comment]
Note that log 0.3 and 0.4 can coexist in the single binary, but don't work exactly great with each other, so I think at least minimal testing to check that logs to work is required.

**Comment by DarkEld3r** [comment]
I propose to mention potential 0.3 and 0.4 issues in the changelog. Something like "Log dependency was updated to 0.4, which can cause issues with previous versions".

**Pull request merged**
