### PR TITLE
Implement `FromStr` for public sodium types.

### LINKED ISSUE #317: Missing `FromStr` impelementations for types that can be converted from hex.
There are no `FromStr` implementation for types like `PublicKey`, so `Context` in clap fabric module can't get these types from arguments directly.

### PR DESCRIPTION
**Pull request by alekseysidorov**
Closes #317

### CODE REVIEW

**Comment by vldm** [comment]
Can you implement `https://doc.rust-lang.org/alloc/string/trait.ToString.html` for public types as well.
(there should be only one convenient way to represent public types)
And may be implement `FromStr` for sodium private types?

**Comment by alekseysidorov** [comment]
In my opinion, for private types it is necessary for a developer to know exactly what he is doing.

**Comment by ivanovaleksey** [comment]
Hello everyone, why `ToString` was implemented?
Wouldn't it be better to implement `Display`?

**Comment by ivanovaleksey** [comment]
Thanks @vitvakatu, will make a PR soon.

**Pull request merged**
