### PR TITLE
Re-use #is_aborted method:

### PR DESCRIPTION
**Pull request by dmitry-timofeev**
## Overview

Re-use #is_aborted method in #finish impl.

---

See: https://jira.bf.local/browse/ECR-XYZW

### Definition of Done

- [ ] There are no TODOs left in the merged code
- [ ] Change is covered by automated tests
- [ ] Benchmark results are attached (if applicable)
- [ ] The [coding guidelines] are followed
- [ ] Public API has proper documentation
- [ ] Changelog is updated if needed (in case of notable or breaking changes)
- [ ] The continuous integration build passes

[coding guidelines]: https://github.com/exonum/exonum/blob/master/CONTRIBUTING.md#conventions

### CODE REVIEW

**Comment by dmitry-timofeev** [comment]
#finish is similar to #merge, so I request Rust-guys to review bigger deduplication opportunities there (e.g., if we don't care if finish creates a new fork (as merge does).

**Comment by popzxc** [comment]
Yeah, that's a good point, but I think we can defer all the refactoring to post-1.0 time.
Now, let's do a (hopefully not last) big dash and reach this milestone :)

**Comment by slowli** [comment]
The code was written this way because of the borrow checker (one thing distinguishing Rust from Java 🙃). As you may see, the changed version has failed to compile:

```text
error[E0382]: borrow of moved value: `self`
   --> components/merkledb/src/migration.rs:530:12
    |
528 |         let patch = self.fork.unwrap().into_patch();
    |                     --------- value moved here
529 |         let hash = Migration::new(&self.namespace, &patch).state_hash();
530 |         if self.is_aborted() {
    |            ^^^^ value borrowed here after partial move
    |
    = note: move occurs because `self.fork` has type `std::option::Option<db::Fork>`, which does not implement the `Copy` trait
```

The gist is that the compiler doesn't (want to?) see that `self.is_aborted()` doesn't use `self.fork`.

**Comment by dmitry-timofeev** [comment]
I see, thanks, so it doesn't work because a part of the object state was already "moved" and after that you can't take a reference to the original object, does it?

This could work if we don't care if it checks the abort signal exactly before the merge. This version does compile:

```rust
        if self.is_aborted() {
            Err(MigrationError::Aborted)
        } else {
            let patch = self.fork.unwrap().into_patch();
            let hash = Migration::new(&self.namespace, &patch).state_hash();
            self.db.merge(patch).map_err(MigrationError::Merge)?;
            Ok(hash)
        }
    }
```

**Comment by slowli** [comment]
@dmitry-timofeev The following works too:

```rust
pub fn finish(mut self) -> Result<Hash, MigrationError> {
    let patch = self.fork.take().unwrap().into_patch();
    let hash = Migration::new(&self.namespace, &patch).state_hash();
    if self.is_aborted() {
        Err(MigrationError::Aborted)
    } else {
        self.db.merge(patch).map_err(MigrationError::Merge)?;
        Ok(hash)
    }
}
```

Note the use of [`Option::take`](https://doc.rust-lang.org/std/option/enum.Option.html#method.take) on `self.fork`. This allows to take out `fork` from `self` without the `MigrationHelper` instance considered partially moved.

**Comment by dmitry-timofeev** [comment]
Thanks! Shall I update the PR with one of the suggested solutions, or close the PR and keep the code as is?

**Comment by slowli** [comment]
@dmitry-timofeev I'd suggest to update this PR with my suggestion since it does not move the abortion check further from the merge application (creating a patch from a fork can take a surprising amount of time).

**Pull request merged**
